name: Deploy Static Website to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2 Ubuntu Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/Palemath-New
          git pull origin main
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/
          sudo systemctl restart nginx
        EOF
